### PR TITLE
Add support for calling .loneElement on NonEmptyList

### PR DESCRIPTION
**Pull request by LeifW**
http://www.scalatest.org/user_guide/using_matchers#singleElementCollections

### CODE REVIEW

**Comment by coltfred** [comment]
@LeifW Would you be willing to write a test showing the expected behavior? I'm opening a PR to fix an issue with cats 1.4 and this library and then will cut a release.

**Comment by LeifW** [comment]
@coltfred Sure, I'll push up a test for this.

**Comment by coltfred** [comment]
Thanks for taking care of the Travis yaml too.

**Comment by coltfred** [comment]
@LeifW Ping.

**Comment by coltfred** [comment]
Help me @LeifW, you're my only hope!

**Comment by coltfred** [comment]
Closed by #47

**Pull request closed without merging**
